# ruby encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Word.create(:jap => "家|いえ", :eng => "house")
Word.create(:jap => "いいえ", :eng => "no")
Word.create(:jap => "絵|え", :eng => "picture")
Word.create(:jap => "ええ", :eng => "yes")
Word.create(:jap => "えいが", :eng => "movie")
Word.create(:jap => "英語|えいご", :eng => "English")
Word.create(:jap => "ドイツ語|ドイツご", :eng => "German (language)")
Word.create(:jap => "私はドイツ人です", :eng => "I'm German")
Word.create(:jap => "かご", :eng => "basket")
Word.create(:jap => "木|き", :eng => "tree")
Word.create(:jap => "子|こ", :eng => "child (short word)")
Word.create(:jap => "声|こえ", :eng => "voice")
Word.create(:jap => "明日|あした", :eng => "tomorrow")
Word.create(:jap => "朝|あさ", :eng => "morning")
Word.create(:jap => "いす", :eng => "chair")
Word.create(:jap => "いつ", :eng => "when")
Word.create(:jap => "うち", :eng => "home")
Word.create(:jap => "学生|がくせい", :eng => "student")
Word.create(:jap => "まちがい", :eng => "mistake")
Word.create(:jap => "方|かた", :eng => "person (polite)")
Word.create(:jap => "ぎし", :eng => "engineer")
Word.create(:jap => "そう", :eng => "so...")
Word.create(:jap => "大学|だいがく", :eng => "university")
Word.create(:jap => "つくえ", :eng => "table")
Word.create(:jap => "どう", :eng => "how")
Word.create(:jap => "どうぞ", :eng => "welcome")
Word.create(:jap => "はじめまして", :eng => "Nice to meet you.")
Word.create(:jap => "よろしくお願いします|よろしくおねがいします", :eng => "Please treat me well.")
Word.create(:jap => "十|じゅう", :eng => "ten")
Word.create(:jap => "今日|きょう", :eng => "today")
Word.create(:jap => "行く|いく", :eng => "to go")
Word.create(:jap => "行う|おこなう", :eng => "do, perform")
Word.create(:jap => "私たち|わたしたち", :eng => "we")
Word.create(:jap => "そうじき", :eng => "vacuum cleaner")
Word.create(:jap => "国|くに", :eng => "country")
Word.create(:jap => "あなた", :eng => "you")
Word.create(:jap => "あの人|あのひと", :eng => "he|she")
Word.create(:jap => "あの方|あのかた", :eng => "he (polite)|she (polite)")
Word.create(:jap => "犬|いぬ", :eng => "dog")
Word.create(:jap => "かべ", :eng => "wall")
Word.create(:jap => "ざっし", :eng => "magazine")
Word.create(:jap => "地図|ちず", :eng => "map")
Word.create(:jap => "ねこ", :eng => "cat")
Word.create(:jap => "はこ", :eng => "box")
Word.create(:jap => "花|はな", :eng => "flower")
Word.create(:jap => "人|ひと", :eng => "person")
Word.create(:jap => "ふで", :eng => "brush")
Word.create(:jap => "聞いてください|きいてください", :eng => "Listen!")
Word.create(:jap => "言ってください|いってください", :eng => "Say!")
Word.create(:jap => "答えてください|こたえてください", :eng => "Answer!")
Word.create(:jap => "おかけください", :eng => "Sit down please!")
Word.create(:jap => "どこからきましたか", :eng => "Where do you come from?")
Word.create(:jap => "何さいですか|なんさいですか", :eng => "How old are you?")
Word.create(:jap => "その通りです|そのとおりです", :eng => "Exactly!")
Word.create(:jap => "ぺこぺこ", :eng => "I'm hungry!")
Word.create(:jap => "よくできました", :eng => "Well done.")
Word.create(:jap => "耳|みみ", :eng => "ear")
Word.create(:jap => "いみ", :eng => "sense")
Word.create(:jap => "ねむい", :eng => "sleepy")
Word.create(:jap => "私はねむいです", :eng => "I'm sleepy")
Word.create(:jap => "紙|かみ", :eng => "paper")
Word.create(:jap => "きもの", :eng => "kimono")
Word.create(:jap => "教か書|きょうかしょ", :eng => "text book")
Word.create(:jap => "教室|きょうしつ", :eng => "class room")
Word.create(:jap => "手紙|てがみ", :eng => "letter")
Word.create(:jap => "まど", :eng => "window")
Word.create(:jap => "水|みず", :eng => "water")
Word.create(:jap => "休み|やすみ", :eng => "holiday|rest")
Word.create(:jap => "山|サン|やま", :eng => "mountain")
Word.create(:jap => "ゆか", :eng => "floor")
Word.create(:jap => "ようふく", :eng => "clothes")
Word.create(:jap => "はい", :eng => "yes")
Word.create(:jap => "直してください|なおしてください", :eng => "correct it!")
Word.create(:jap => "もういちどどうぞ", :eng => "one more time!")
Word.create(:jap => "お茶|おちゃ", :eng => "tea")
Word.create(:jap => "紅茶|こうちゃ", :eng => "black tea")
Word.create(:jap => "東京で何をしますか|とうきょうでなにをしますか", :eng => "What do you do in Tokyo?")
Word.create(:jap => "お名前|おなまえ", :eng => "name")
Word.create(:jap => "むだばなし", :eng => "quatsch")
Word.create(:jap => "本|ほん", :eng => "book")
Word.create(:jap => "れいぞうこ", :eng => "fridge")
Word.create(:jap => "かばん", :eng => "bag|backpack")
Word.create(:jap => "終わり|おわり", :eng => "end")
Word.create(:jap => "こくばん", :eng => "blackboard")
Word.create(:jap => "写真|しゃしん", :eng => "foto")
Word.create(:jap => "新聞|新ぶん|しんぶん", :eng => "newspaper")
Word.create(:jap => "先生|せんせい", :eng => "teacher")
Word.create(:jap => "電話|でんわ", :eng => "telephone")
Word.create(:jap => "番号|ばんごう", :eng => "number")
Word.create(:jap => "電話番号は何ですか|でんわばんごうはなんですか", :eng => "What's your number?")
Word.create(:jap => "日本|にほん", :eng => "Japan")
Word.create(:jap => "文れい|ぶんれい", :eng => "example")
Word.create(:jap => "べんきょう", :eng => "study")
Word.create(:jap => "皆さん|みなさん", :eng => "Dear all")
Word.create(:jap => "皆|みんな", :eng => "everyone")
Word.create(:jap => "いいえ、これはちがいます", :eng => "No, it's different / not correct")
Word.create(:jap => "わかりますか", :eng => "Do you understand?")
Word.create(:jap => "読んでください|よんでください", :eng => "Read it, please    ")
Word.create(:jap => "日本語で話してください|にほんごではなしてください", :eng => "Say it in Japanese, please.")
Word.create(:jap => "むだづかい", :eng => "wasted use ")
Word.create(:jap => "ばか", :eng => "stupid|idiot ")
Word.create(:jap => "外人|がいじん", :eng => "foreigner")
Word.create(:jap => "ぼく", :eng => "I")
Word.create(:jap => "ではありません", :eng => "isn't")
Word.create(:jap => "Nは何ですか", :eng => "What is N?")
Word.create(:jap => "もちろんです", :eng => "Of course, certainly")
Word.create(:jap => "NはN2ですか", :eng => "N2 (question word) is N?")
Word.create(:jap => "だれ|どなた", :eng => "who")
Word.create(:jap => "さま", :eng => "master (super-polite)")
Word.create(:jap => "お金|おかね", :eng => "money")
Word.create(:jap => "ほんやくしてください", :eng => "Translate, please!")
Word.create(:jap => "れきし", :eng => "history")
Word.create(:jap => "けいざい", :eng => "economy")
Word.create(:jap => "いしゃ", :eng => "doctor")
Word.create(:jap => "せんもん", :eng => "specialty (subject of study)")
Word.create(:jap => "これ", :eng => "this")
Word.create(:jap => "ペン", :eng => "pen")
Word.create(:jap => "あれ", :eng => "that (but far)")
Word.create(:jap => "たな", :eng => "shelf")
Word.create(:jap => "ドア", :eng => "door")
Word.create(:jap => "えんぴつ", :eng => "pencil")
Word.create(:jap => "一年生|いちねんせい", :eng => "first year student")
Word.create(:jap => "ノート", :eng => "notebook")
Word.create(:jap => "どれ", :eng => "which")
Word.create(:jap => "じ書|じしょ", :eng => "dictionary")
Word.create(:jap => "図書館|としょかん", :eng => "library")
Word.create(:jap => "文学部|ぶんがくぶ", :eng => "literature department")
Word.create(:jap => "とけい", :eng => "watch")
Word.create(:jap => "大学生|だいがくせい", :eng => "university student")
Word.create(:jap => "でんとう", :eng => "lamp")
Word.create(:jap => "おわりました", :eng => "I understood")
Word.create(:jap => "ありがとうございます", :eng => "Thank you very much")
Word.create(:jap => "どういたしまして", :eng => "You're welcome")
Word.create(:jap => "スイス", :eng => "swiss")
Word.create(:jap => "ソーセージ", :eng => "sausage")
Word.create(:jap => "アジア", :eng => "asia")
Word.create(:jap => "ウィスキ", :eng => "whisky")
Word.create(:jap => "クイズ", :eng => "quiz")
Word.create(:jap => "ココア", :eng => "cocoa")
Word.create(:jap => "サイズ", :eng => "size")
Word.create(:jap => "サカス", :eng => "circus")
Word.create(:jap => "センス", :eng => "sense (foreign)")
Word.create(:jap => "ソース", :eng => "souce")
Word.create(:jap => "エアコン", :eng => "air conditioning")
Word.create(:jap => "コイン", :eng => "coin")
Word.create(:jap => "サイエンス", :eng => "science")
Word.create(:jap => "ケーキ", :eng => "cake")
Word.create(:jap => "スキーウェア", :eng => "ski wear")
Word.create(:jap => "いとこ", :eng => "cousin")
Word.create(:jap => "すきな", :eng => "favorite")
Word.create(:jap => "のみもの", :eng => "drink")
Word.create(:jap => "すきなえいがは何ですか|すきなえいがはなんですか", :eng => "What's your favorite movie?")
Word.create(:jap => "母|はは", :eng => "mother")
Word.create(:jap => "お母さん|おかあさん", :eng => "mother (polite)")
Word.create(:jap => "父|ちち", :eng => "father")
Word.create(:jap => "お父さん|おとうさん", :eng => "father (polite)")
Word.create(:jap => "妹|いもうと", :eng => "younger sister ")
Word.create(:jap => "姉|あね", :eng => "older sister")
Word.create(:jap => "弟|おとうと", :eng => "younger brother")
Word.create(:jap => "兄|あに", :eng => "older brother")
Word.create(:jap => "むすこ", :eng => "son")
Word.create(:jap => "むすめ", :eng => "daughter")
Word.create(:jap => "留学生|りゅうがくせい", :eng => "exchange student")
Word.create(:jap => "この", :eng => "this (thing)")
Word.create(:jap => "たてもの", :eng => "building")
Word.create(:jap => "あそこ", :eng => "over there (far)")
Word.create(:jap => "ここ", :eng => "here")
Word.create(:jap => "その", :eng => "this (thing) (yours)")
Word.create(:jap => "あの", :eng => "that (thing) (over there)")
Word.create(:jap => "どこ", :eng => "where")
Word.create(:jap => "どの", :eng => "which (thing)")
Word.create(:jap => "部屋|へや", :eng => "room")
Word.create(:jap => "ちり学|ちりがく", :eng => "geography")
Word.create(:jap => "図書室|としょしつ", :eng => "library room")
Word.create(:jap => "グループ", :eng => "group")
Word.create(:jap => "アメリカ人", :eng => "american person")
Word.create(:jap => "チョーク", :eng => "chalk")
Word.create(:jap => "けしゴム", :eng => "eraser")
Word.create(:jap => "次|つぎ", :eng => "next")
Word.create(:jap => "授業|じゅぎょう", :eng => "lesson")
Word.create(:jap => "おはようございます", :eng => "good morning")
Word.create(:jap => "こんにちは", :eng => "good day (good morning)")
Word.create(:jap => "こんばんは", :eng => "good evening")
Word.create(:jap => "さようなら", :eng => "goodbye")
Word.create(:jap => "では|また", :eng => "bye")
Word.create(:jap => "これはほんやくしてください", :eng => "Translate this, please")
Word.create(:jap => "ぶつり学|ぶつりがく", :eng => "physics")
Word.create(:jap => "ちしつ学|ちしつがく", :eng => "geology")
Word.create(:jap => "しつ問|しつもん", :eng => "question")
Word.create(:jap => "かんたん", :eng => "simple")
Word.create(:jap => "むずかしい", :eng => "difficult")
Word.create(:jap => "おいしい", :eng => "tasty")
Word.create(:jap => "美しい|うつくしい", :eng => "beautiful")
Word.create(:jap => "とても", :eng => "very")
Word.create(:jap => "しゅくだい", :eng => "homework")
Word.create(:jap => "半分|はんぶん", :eng => "half")
Word.create(:jap => "しゅくだいをかくにんしましょう", :eng => "Let's check homework")
Word.create(:jap => "アレルギー", :eng => "allergy")
Word.create(:jap => "ユーザー", :eng => "user")
Word.create(:jap => "メニュー", :eng => "menu")
Word.create(:jap => "レポート", :eng => "report")
Word.create(:jap => "ワイシャツ", :eng => "white shirt")
Word.create(:jap => "ワンピース", :eng => "one piece")
Word.create(:jap => "さいご", :eng => "last")
Word.create(:jap => "私はNがあります", :eng => "I have N")
Word.create(:jap => "たくさん", :eng => "a lot")
Word.create(:jap => "赤い|あかい", :eng => "red")
Word.create(:jap => "青い|あおい", :eng => "blue")
Word.create(:jap => "寒い|さむい", :eng => "cold")
Word.create(:jap => "せまい", :eng => "narrow")
Word.create(:jap => "やさしい", :eng => "easy")
Word.create(:jap => "古い|ふるい", :eng => "old")
Word.create(:jap => "面白い|おもしろい", :eng => "interesting")
Word.create(:jap => "白い|しろい", :eng => "white")
Word.create(:jap => "つまらない", :eng => "boring")
Word.create(:jap => "長い|ながい", :eng => "long")
Word.create(:jap => "週|しゅう", :eng => "week")
Word.create(:jap => "毎週|まいしゅう", :eng => "every week")
Word.create(:jap => "今週|こんしゅう", :eng => "this week")
Word.create(:jap => "先週|せんしゅう", :eng => "last week")
Word.create(:jap => "どんな", :eng => "which (characteristics)")
Word.create(:jap => "すこし", :eng => "a little")
Word.create(:jap => "ちょっと", :eng => "a little bit")
Word.create(:jap => "あいにく", :eng => "unfortunately")
Word.create(:jap => "りんご", :eng => "apple")
Word.create(:jap => "東京|とうきょう", :eng => "Tokyo|eastern capital")
Word.create(:jap => "広い|ひろい", :eng => "wide")
Word.create(:jap => "近い|ちかい", :eng => "close")
Word.create(:jap => "高い|たかい", :eng => "tall|expensive")
Word.create(:jap => "茶色い|ちゃいろい", :eng => "tea color|brown")
Word.create(:jap => "新しい|あたらしい", :eng => "new")
Word.create(:jap => "あまり", :eng => "not very")
Word.create(:jap => "黄色い|きいろい", :eng => "yellow")
Word.create(:jap => "こちら", :eng => "this way, this direction, here")
Word.create(:jap => "こちらこそ", :eng => "The pleasure is all mine")
Word.create(:jap => "お宅|おたく", :eng => "yours, your house")
Word.create(:jap => "遠い|とおい", :eng => "far (away)")
Word.create(:jap => "良い|いい", :eng => "good")
Word.create(:jap => "明るい|あかるい", :eng => "bright, light")
Word.create(:jap => "黒い|くろい", :eng => "black")
Word.create(:jap => "緑色|みどりいろ", :eng => "green")
Word.create(:jap => "色|いろ", :eng => "color")
Word.create(:jap => "短い|みじかい", :eng => "short")
Word.create(:jap => "安い|やすい", :eng => "cheap")
Word.create(:jap => "ひくい", :eng => "low, short")
Word.create(:jap => "カメラ", :eng => "camera")
Word.create(:jap => "小さい|ちいさい", :eng => "small")
Word.create(:jap => "すこしも", :eng => "not at all")
Word.create(:jap => "ちっとも", :eng => "not at all!!!")
Word.create(:jap => "テキスト", :eng => "text")
Word.create(:jap => "ろうか", :eng => "corridor")
Word.create(:jap => "たいへん", :eng => "very, greatly|enormously")
Word.create(:jap => "もの", :eng => "thing")
Word.create(:jap => "では", :eng => "So... then...")
Word.create(:jap => "ねずみ", :eng => "mouse")
Word.create(:jap => "ねずみいろ", :eng => "grey (mouse color)")
Word.create(:jap => "みかん", :eng => "mandarin")
Word.create(:jap => "みかんいろ", :eng => "mandarine color")
Word.create(:jap => "もも", :eng => "peach")
Word.create(:jap => "ももいろ", :eng => "peach color")
Word.create(:jap => "オレンジ", :eng => "orange")
Word.create(:jap => "オレンジいろ", :eng => "orange color")
Word.create(:jap => "始めてください|はじめてください", :eng => "please begin")
Word.create(:jap => "全部|ぜんぶ", :eng => "all, everything, entire")
Word.create(:jap => "アダプタ", :eng => "adapter")
Word.create(:jap => "ロケット", :eng => "rocket")
Word.create(:jap => "エレベータ", :eng => "elevator")
Word.create(:jap => "スポーツ", :eng => "sports")
Word.create(:jap => "パン", :eng => "bread")
Word.create(:jap => "買う|かう", :eng => "to buy")
Word.create(:jap => "書く|かく", :eng => "to write")
Word.create(:jap => "急ぐ|いそぐ", :eng => "to be in a hurry")
Word.create(:jap => "話す|はなす", :eng => "to speak")
Word.create(:jap => "立つ|たつ", :eng => "to stand")
Word.create(:jap => "死ぬ|しぬ", :eng => "to die")
Word.create(:jap => "とぶ", :eng => "to fly")
Word.create(:jap => "飲む|のむ", :eng => "to drink")
Word.create(:jap => "売る|うる", :eng => "to sell")
Word.create(:jap => "ある", :eng => "to be (things)")
Word.create(:jap => "見る|みる", :eng => "to see")
Word.create(:jap => "いる", :eng => "to be")
Word.create(:jap => "食べる|たべる", :eng => "to eat")
Word.create(:jap => "える", :eng => "to get/gain")
Word.create(:jap => "走る|はしる", :eng => "to run")
Word.create(:jap => "入る|はいる", :eng => "to enter")
Word.create(:jap => "帰る|かえる", :eng => "to return")
Word.create(:jap => "する", :eng => "to do")
Word.create(:jap => "来る|くる", :eng => "to come")
Word.create(:jap => "指す|さす", :eng => "to stab (pieken)")
Word.create(:jap => "取る|とる", :eng => "to take")
Word.create(:jap => "今夜|こんや", :eng => "this evening")
Word.create(:jap => "時間|じかん", :eng => "time")
Word.create(:jap => "分|ぶん", :eng => "minute")
Word.create(:jap => "年|とし", :eng => "year")
Word.create(:jap => "遅い|おそい", :eng => "late")
Word.create(:jap => "早い|はやい", :eng => "early|quick")
Word.create(:jap => "時|じ", :eng => "hour")
Word.create(:jap => "夕|ゆう", :eng => "evening")
Word.create(:jap => "午後|ごご", :eng => "afternoon")
Word.create(:jap => "毎朝|まいあさ", :eng => "every morning")
Word.create(:jap => "起きる|おきる", :eng => "to get up|to wake up")
Word.create(:jap => "たいてい", :eng => "mostly")
Word.create(:jap => "午前|ごぜん", :eng => "a.m.|before noon")
Word.create(:jap => "始まる|はじまる", :eng => "to begin")
Word.create(:jap => "毎日|まいにち", :eng => "every day")
Word.create(:jap => "昼休み|ひるやすみ", :eng => "lunch break")
Word.create(:jap => "食堂|しょくどう", :eng => "cafeteria|dining hall")
Word.create(:jap => "時々|ときどき", :eng => "sometimes")
Word.create(:jap => "喫茶店|きっさてん", :eng => "café")
Word.create(:jap => "いそがしい", :eng => "busy")
Word.create(:jap => "毎晩|まいばん", :eng => "every night")
Word.create(:jap => "べんきょうする", :eng => "to study")
Word.create(:jap => "ねる", :eng => "to sleep")
Word.create(:jap => "今ど|こんど", :eng => "this time")
Word.create(:jap => "ゆっくり", :eng => "slowly|at ease")
Word.create(:jap => "うえの", :eng => "Ueno, section of Tokyo")
Word.create(:jap => "ふつう", :eng => "usually|normally")
Word.create(:jap => "また", :eng => "also")
Word.create(:jap => "何曜日|なんようび", :eng => "What day of the week?")
Word.create(:jap => "何時|なんじ", :eng => "What time?")
Word.create(:jap => "さんぽする", :eng => "to take a walk")
Word.create(:jap => "さんぽ", :eng => "walk")
Word.create(:jap => "夜|よる", :eng => "night")
Word.create(:jap => "今年|ことし", :eng => "this year")
Word.create(:jap => "その後で|そのあとで", :eng => "after that")
Word.create(:jap => "直ぐ|すぐ", :eng => "immediately|soon")
Word.create(:jap => "ぎんざ", :eng => "Shopping district in Tokyo")
Word.create(:jap => "クラブ", :eng => "club")
Word.create(:jap => "れん習|れんしゅう", :eng => "practise")
Word.create(:jap => "安心|あんしん", :eng => "peace of mind")
Word.create(:jap => "段々|だんだん", :eng => "gradually|step by step")
Word.create(:jap => "段|だん", :eng => "step")
Word.create(:jap => "動く|うごく", :eng => "to move")
Word.create(:jap => "研究|けんきゅう", :eng => "research")
Word.create(:jap => "じっけん", :eng => "experiment")
Word.create(:jap => "そつぎょう", :eng => "graduation")
Word.create(:jap => "悪化|あっか", :eng => "deterioration|worsening")
Word.create(:jap => "ほうそう", :eng => "show|stream|broadcast")
Word.create(:jap => "考える|かんがえる", :eng => "to think")
Word.create(:jap => "考え|かんがえ", :eng => "thought")
Word.create(:jap => "あそぶ", :eng => "to play")
Word.create(:jap => "のこる", :eng => "to remain|to be left over")
Word.create(:jap => "人々|ひとびと", :eng => "people")
Word.create(:jap => "ます", :eng => "to increase")
Word.create(:jap => "ますます", :eng => "more and more")
Word.create(:jap => "じぶん", :eng => "yourself|your")
Word.create(:jap => "かんぺき", :eng => "perfect")
Word.create(:jap => "まじめ", :eng => "streber")
Word.create(:jap => "間|あいだ", :eng => "between")
Word.create(:jap => "休けい|きゅうけい", :eng => "break")
Word.create(:jap => "自分|じぶん", :eng => "myself")
Word.create(:jap => "きのう", :eng => "yesterday")
Word.create(:jap => "直す|なおす", :eng => "to correct")
Word.create(:jap => "シャワ", :eng => "shower")
Word.create(:jap => "シャワを浴びる|シャワをあびる", :eng => "to take a shower")
Word.create(:jap => "歯をみがく|はをみがく", :eng => "to brush teeth")
Word.create(:jap => "ホーム・ステイ", :eng => "home stay")
Word.create(:jap => "門|もん", :eng => "gate|entrance")
Word.create(:jap => "松|まつ", :eng => "pine tree")
Word.create(:jap => "庭|にわ", :eng => "(personal) garden")
Word.create(:jap => "さくら", :eng => "cherry (blossom) tree")
Word.create(:jap => "竹|たけ", :eng => "bamboo")
Word.create(:jap => "池|いけ", :eng => "pond")
Word.create(:jap => "こい", :eng => "koi")
Word.create(:jap => "橋|はし", :eng => "bridge")
Word.create(:jap => "階|かい", :eng => "story of a building")
Word.create(:jap => "おうせつ間|おうせつま", :eng => "european room")
Word.create(:jap => "茶の間|ちゃのま", :eng => "japanese living room")
Word.create(:jap => "トイレ", :eng => "toilet")
Word.create(:jap => "おふろ", :eng => "bathroom (jap. style)")
Word.create(:jap => "右側|みぎがわ", :eng => "right")
Word.create(:jap => "左側|ひだりがわ", :eng => "left")
Word.create(:jap => "台所|だいどころ", :eng => "kitchen")
Word.create(:jap => "階段|かいだん", :eng => "staircase")
Word.create(:jap => "子ども|こども", :eng => "child")
Word.create(:jap => "日本間|にほんま", :eng => "japanese room")
Word.create(:jap => "たたみ", :eng => "Tatami")
Word.create(:jap => "おしいれ", :eng => "closet (with sliding door)")
Word.create(:jap => "本だな|ほんだな", :eng => "book shelf")
Word.create(:jap => "いくつ", :eng => "how many")
Word.create(:jap => "何階|なんがい", :eng => "what floor?")
Word.create(:jap => "よう間|ようま", :eng => "western style room")
Word.create(:jap => "よう式|ようしき", :eng => "western style")
Word.create(:jap => "日本式|にほんしき", :eng => "japanese style")
Word.create(:jap => "魚|さかな", :eng => "fish")
Word.create(:jap => "銀行|ぎんこう", :eng => "bank")
Word.create(:jap => "銀行家|ぎんこうか", :eng => "banker")
Word.create(:jap => "デパート", :eng => "department store")
Word.create(:jap => "公園|こうえん", :eng => "public park")
Word.create(:jap => "ビデオ", :eng => "video")
Word.create(:jap => "アルバム", :eng => "album")
Word.create(:jap => "からす", :eng => "crow")
Word.create(:jap => "パン屋|ぱんや", :eng => "bakery")
Word.create(:jap => "学校|がっこう", :eng => "school")
Word.create(:jap => "駅|えき", :eng => "station")
Word.create(:jap => "バナナ", :eng => "banana")
Word.create(:jap => "ベンチ", :eng => "bench")
Word.create(:jap => "かさ", :eng => "umbrella")
Word.create(:jap => "くつ", :eng => "shoes")
Word.create(:jap => "鳥|とり", :eng => "bird")
Word.create(:jap => "となり", :eng => "near")
Word.create(:jap => "そば", :eng => "next to")
Word.create(:jap => "後ろ|うしろ", :eng => "behind")
Word.create(:jap => "外|そと", :eng => "outside")
Word.create(:jap => "見つける|みつける", :eng => "to find")
Word.create(:jap => "さがす", :eng => "to look for")
Word.create(:jap => "けいたい電話|けいたいでんわ", :eng => "mobile phone")
Word.create(:jap => "太よう|たいよう", :eng => "sun")
Word.create(:jap => "一人で|ひとりで", :eng => "alone")
Word.create(:jap => "文法|ぶんぽう", :eng => "grammar")
Word.create(:jap => "イギリス", :eng => "United Kingdom|Great Britain")
Word.create(:jap => "天井|てんじょう", :eng => "ceiling")
Word.create(:jap => "コート", :eng => "coat")
Word.create(:jap => "ソファ", :eng => "sofa")
Word.create(:jap => "つかれる", :eng => "to get tired")
Word.create(:jap => "どうして", :eng => "why")
Word.create(:jap => "少ない|すくない", :eng => "a few")
Word.create(:jap => "私はよくねませんでした|わたしはよくねませんでした", :eng => "I didn't sleep well")
Word.create(:jap => "一昨日|おととい", :eng => "the day before yesterday")
Word.create(:jap => "せいこう", :eng => "success")
Word.create(:jap => "もどる", :eng => "to be back")
Word.create(:jap => "向かう|むかう", :eng => "facing")
Word.create(:jap => "たとえば", :eng => "For example")
Word.create(:jap => "パソコン", :eng => "personal computer")
Word.create(:jap => "自分で食事を作りますか|じぶんでしょくじをつくりますか", :eng => "Do you make the meal yourself?")
Word.create(:jap => "言ば|ことば", :eng => "word")
Word.create(:jap => "おもちゃ", :eng => "toy")
Word.create(:jap => "色々な|いろいろな", :eng => "various")
Word.create(:jap => "明後日|あさって", :eng => "the day after tomorrow")
Word.create(:jap => "作る|つくる", :eng => "to make")
Word.create(:jap => "Nについて", :eng => "about N")
Word.create(:jap => "食事|しょくじ", :eng => "meal")
Word.create(:jap => "始め|はじめ", :eng => "beginning|start")
Word.create(:jap => "はつおん", :eng => "pronounciation")
Word.create(:jap => "れん習|れんしゅう", :eng => "exercise")
Word.create(:jap => "文しょう|ぶんしょう", :eng => "sentence|article")
Word.create(:jap => "読む|よむ", :eng => "to read")
Word.create(:jap => "文けい|ぶんけい", :eng => "sentence pattern|sentence example")
Word.create(:jap => "出す|だす", :eng => "to give|to put out")
Word.create(:jap => "もう", :eng => "already|yet")
Word.create(:jap => "会話|かいわ", :eng => "dialog|conversation")
Word.create(:jap => "答える|こたえる", :eng => "to answer")
Word.create(:jap => "その他|そのほか", :eng => "besides|otherwise")
Word.create(:jap => "スピーチ", :eng => "speech")
Word.create(:jap => "事情|じじょう", :eng => "situation")
Word.create(:jap => "教える|おしえる", :eng => "to teach")
Word.create(:jap => "習う|ならう", :eng => "to learn")
Word.create(:jap => "講義|こうぎ", :eng => "lecture")
Word.create(:jap => "聞く|きく", :eng => "to hear")
Word.create(:jap => "間違える|まちがえる", :eng => "to make a mistake")
Word.create(:jap => "テープ", :eng => "tape")
Word.create(:jap => "ニュース", :eng => "news")
Word.create(:jap => "見せる|みせる", :eng => "to show")
Word.create(:jap => "おく", :eng => "to place sth sw")
Word.create(:jap => "歩く|あるく", :eng => "to walk")
Word.create(:jap => "足|あし", :eng => "leg")
Word.create(:jap => "手|て", :eng => "hand")
Word.create(:jap => "目|め", :eng => "eye")
Word.create(:jap => "口|くち", :eng => "mouth")
Word.create(:jap => "ごはん", :eng => "cooked rice")
Word.create(:jap => "多い|おおい", :eng => "many")
Word.create(:jap => "音|おと", :eng => "sound")
Word.create(:jap => "テレビ", :eng => "television")
Word.create(:jap => "本当|ほんとう", :eng => "really")
Word.create(:jap => "両親|りょうしん", :eng => "parents")
Word.create(:jap => "ラジオ", :eng => "radio")
Word.create(:jap => "答え|こたえ", :eng => "answer")
Word.create(:jap => "かく", :eng => "to paint|to draw")
Word.create(:jap => "テスト", :eng => "test")
Word.create(:jap => "せんたく", :eng => "laundry")
Word.create(:jap => "うでどけい", :eng => "wrist watch")
Word.create(:jap => "そうじ", :eng => "cleaning")
Word.create(:jap => "そうじする", :eng => "to clean")
Word.create(:jap => "冬|ふゆ", :eng => "winter")
Word.create(:jap => "夏|なつ", :eng => "summer")
Word.create(:jap => "秋|あき", :eng => "autumn")
Word.create(:jap => "春|はる", :eng => "spring")
Word.create(:jap => "何時も|いつも", :eng => "always")
Word.create(:jap => "仕事|しごと", :eng => "work")
Word.create(:jap => "おみやげ", :eng => "souvenirs")
Word.create(:jap => "へんじ", :eng => "reply")
Word.create(:jap => "ひこうき", :eng => "airplane")
Word.create(:jap => "よい", :eng => "good (how do you say it normally)")
Word.create(:jap => "なぜ", :eng => "why")
Word.create(:jap => "果物|くだもの", :eng => "fruits")
Word.create(:jap => "果物屋|くだものや", :eng => "fruit shop")
Word.create(:jap => "愛|あい", :eng => "love")
Word.create(:jap => "歌|うた", :eng => "song")
Word.create(:jap => "行きたい|いきたい", :eng => "(i) want to go")
Word.create(:jap => "よかったです", :eng => "it was good")
Word.create(:jap => "りっぱな", :eng => "fine|wonderful|sophisticated")
Word.create(:jap => "かのじょ", :eng => "girlfriend")
Word.create(:jap => "私は走ります|わたしははしります", :eng => "I run")
Word.create(:jap => "書いてください|かいてください", :eng => "Write it please!")
Word.create(:jap => "いくら", :eng => "how much")
Word.create(:jap => "めしあがってください", :eng => "Please eat! (politely)")
Word.create(:jap => "二人|ふたり", :eng => "Two persons")
Word.create(:jap => "しずかな", :eng => "quiet")
Word.create(:jap => "ゆうめいな", :eng => "famous|popular")
Word.create(:jap => "音楽|おんがく", :eng => "music")
Word.create(:jap => "お菓子|おかし", :eng => "sweets")
Word.create(:jap => "へいわ", :eng => "peace")
Word.create(:jap => "なし", :eng => "pear")
Word.create(:jap => "きらいな", :eng => "dislike")
Word.create(:jap => "店|みせ", :eng => "shop|store")
Word.create(:jap => "しんせつな", :eng => "kind|accommodating")
Word.create(:jap => "店員|てんいん", :eng => "clerk|shop assistant")
Word.create(:jap => "好きな|すきな", :eng => "to like")
Word.create(:jap => "朝食|ちょうしょく", :eng => "breakfast")
Word.create(:jap => "洋食|ようしょく", :eng => "western style meal")
Word.create(:jap => "サンドイッチ", :eng => "sandwich")
Word.create(:jap => "たまご", :eng => "eggs")
Word.create(:jap => "ジュース", :eng => "juice")
Word.create(:jap => "飲む|のむ", :eng => "to drink|to smoke")
Word.create(:jap => "わ食|わしょく", :eng => "japanese-style food")
Word.create(:jap => "みそしる", :eng => "miso soup")
Word.create(:jap => "わかい", :eng => "young")
Word.create(:jap => "しかし", :eng => "but|however")
Word.create(:jap => "ハム・エッグ", :eng => "ham and eggs")
Word.create(:jap => "サラダ", :eng => "salad")
Word.create(:jap => "いっしょ", :eng => "together")
Word.create(:jap => "そして", :eng => "and")
Word.create(:jap => "大好きな|だいすきな", :eng => "favorite")
Word.create(:jap => "ウエイトレス", :eng => "waitress")
Word.create(:jap => "持ってくる|もってくる", :eng => "bring")
Word.create(:jap => "でも", :eng => "but|however")
Word.create(:jap => "インテリア", :eng => "interior")
Word.create(:jap => "すてきな", :eng => "lovely")
Word.create(:jap => "昼間|ひるま", :eng => "daytime")
Word.create(:jap => "にぎやかな", :eng => "bustling|super busy")
Word.create(:jap => "げんきな", :eng => "healthy")
Word.create(:jap => "きれいな", :eng => "beautiful (thing)")
Word.create(:jap => "まち", :eng => "town")
Word.create(:jap => "かき", :eng => "Kaki-Frucht")
Word.create(:jap => "きたない", :eng => "dirty")
Word.create(:jap => "ダンス", :eng => "dance")
Word.create(:jap => "ばら", :eng => "rose")
Word.create(:jap => "所|ところ", :eng => "place")
Word.create(:jap => "かなり", :eng => "considerably|fairly")
Word.create(:jap => "うるさい", :eng => "noisy|loud")
Word.create(:jap => "注文|ちゅうもん", :eng => "order")
Word.create(:jap => "注文する|ちゅうもんする", :eng => "to give an order")
Word.create(:jap => "しめる", :eng => "to close")
Word.create(:jap => "すみません", :eng => "I'm sorry")
Word.create(:jap => "お待たせいたしました|おまたせいたしました", :eng => "Thank you for waiting")
Word.create(:jap => "じこ", :eng => "accident")
Word.create(:jap => "しょうかい", :eng => "introduction")
Word.create(:jap => "名字|みょうじ", :eng => "last name")
Word.create(:jap => "ゼミ", :eng => "seminar")
Word.create(:jap => "文化|ぶんか", :eng => "culture")
Word.create(:jap => "家族|かぞく", :eng => "family")
Word.create(:jap => "サラリーマン", :eng => "Salary man")
Word.create(:jap => "小学校|しょうがっこう", :eng => "elementary school")
Word.create(:jap => "中学生|ちゅうがくせい", :eng => "junior high school student")
Word.create(:jap => "祖父|そふ", :eng => "grand father (coll.)")
Word.create(:jap => "祖母|そぼ", :eng => "grand mother (coll.)")
Word.create(:jap => "大ぜい|おおぜい", :eng => "crowd")
Word.create(:jap => "あつまり", :eng => "gathering")
Word.create(:jap => "会う|あう", :eng => "to meet")
Word.create(:jap => "ロビー", :eng => "lobby")
Word.create(:jap => "それでは", :eng => "well then|in that case")
Word.create(:jap => "生と|せいと", :eng => "pupil")
Word.create(:jap => "ミーティング", :eng => "meeting")
Word.create(:jap => "それとも", :eng => "and then|or")
Word.create(:jap => "おじさん", :eng => "uncle")
Word.create(:jap => "おばさん", :eng => "aunt")
Word.create(:jap => "おじいさん", :eng => "grand father")
Word.create(:jap => "おばあさん", :eng => "grand mother")
Word.create(:jap => "ジューナリスト", :eng => "journalist")
Word.create(:jap => "真ん中|まんなか", :eng => "middle")
Word.create(:jap => "たいそうする", :eng => "to exercise")
Word.create(:jap => "映画館|えいがかん", :eng => "cinema")
Word.create(:jap => "肉|にく", :eng => "meat")
Word.create(:jap => "肉屋|にくや", :eng => "butchery")
Word.create(:jap => "肉屋さん|にくやさん", :eng => "butcher")
Word.create(:jap => "さとう", :eng => "sugar")
Word.create(:jap => "つま", :eng => "wife")
Word.create(:jap => "週に三回|しゅうにさんかい", :eng => "three times a week")
Word.create(:jap => "去年|きょねん", :eng => "last year")
Word.create(:jap => "かんごふ", :eng => "nurse")
Word.create(:jap => "しけん", :eng => "exam")
Word.create(:jap => "生きる|いきる", :eng => "to live")
Word.create(:jap => "晩ご飯|ばんごはん", :eng => "dinner")
Word.create(:jap => "牛乳|ぎゅうにゅう", :eng => "milk")