# ruby encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

list = WordList.find_or_create_by(:title => 'Japanese basic vocabulary')
list.update_attributes(:author => 'Kai')

Word.find_or_create_by(:back => "家|いえ", :front => "house").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いいえ", :front => "no").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "絵|え", :front => "picture").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ええ", :front => "yes").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "えいが", :front => "movie").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "英語|えいご", :front => "English").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ドイツ語|ドイツご", :front => "German (language)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私はドイツ人です", :front => "I'm German").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かご", :front => "basket").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "木|き", :front => "tree").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "子|こ", :front => "child (short word)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "声|こえ", :front => "voice").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "明日|あした", :front => "tomorrow").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "朝|あさ", :front => "morning").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いす", :front => "chair").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いつ", :front => "when").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "うち", :front => "home").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "学生|がくせい", :front => "student").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "まちがい", :front => "mistake").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "方|かた", :front => "person (polite)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ぎし", :front => "engineer").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そう", :front => "so...").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "大学|だいがく", :front => "university").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "つくえ", :front => "table").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どう", :front => "how").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どうぞ", :front => "welcome").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "はじめまして", :front => "Nice to meet you.").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よろしくお願いします|よろしくおねがいします", :front => "Please treat me well.").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "十|じゅう", :front => "ten").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "今日|きょう", :front => "today").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "行く|いく", :front => "to go").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "行う|おこなう", :front => "do, perform").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私たち|わたしたち", :front => "we").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そうじき", :front => "vacuum cleaner").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "国|くに", :front => "country").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あなた", :front => "you").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あの人|あのひと", :front => "he|she").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あの方|あのかた", :front => "he (polite)|she (polite)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "犬|いぬ", :front => "dog").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かべ", :front => "wall").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ざっし", :front => "magazine").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "地図|ちず", :front => "map").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ねこ", :front => "cat").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "はこ", :front => "box").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "花|はな", :front => "flower").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "人|ひと", :front => "person").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ふで", :front => "brush").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "聞いてください|きいてください", :front => "Listen!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "言ってください|いってください", :front => "Say!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "答えてください|こたえてください", :front => "Answer!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おかけください", :front => "Sit down please!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どこからきましたか", :front => "Where do you come from?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "何さいですか|なんさいですか", :front => "How old are you?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "その通りです|そのとおりです", :front => "Exactly!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ぺこぺこ", :front => "I'm hungry!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よくできました", :front => "Well done.").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "耳|みみ", :front => "ear").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いみ", :front => "sense").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ねむい", :front => "sleepy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私はねむいです", :front => "I'm sleepy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "紙|かみ", :front => "paper").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "きもの", :front => "kimono").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "教か書|きょうかしょ", :front => "text book").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "教室|きょうしつ", :front => "class room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "手紙|てがみ", :front => "letter").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "まど", :front => "window").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "水|みず", :front => "water").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "休み|やすみ", :front => "holiday|rest").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "山|サン|やま", :front => "mountain").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ゆか", :front => "floor").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ようふく", :front => "clothes").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "はい", :front => "yes").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "直してください|なおしてください", :front => "correct it!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もういちどどうぞ", :front => "one more time!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お茶|おちゃ", :front => "tea").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "紅茶|こうちゃ", :front => "black tea").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "東京で何をしますか|とうきょうでなにをしますか", :front => "What do you do in Tokyo?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お名前|おなまえ", :front => "name").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "むだばなし", :front => "quatsch").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "本|ほん", :front => "book").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "れいぞうこ", :front => "fridge").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かばん", :front => "bag|backpack").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "終わり|おわり", :front => "end").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こくばん", :front => "blackboard").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "写真|しゃしん", :front => "foto").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "新聞|新ぶん|しんぶん", :front => "newspaper").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "先生|せんせい", :front => "teacher").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "電話|でんわ", :front => "telephone").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "番号|ばんごう", :front => "number").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "電話番号は何ですか|でんわばんごうはなんですか", :front => "What's your number?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "日本|にほん", :front => "Japan").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文れい|ぶんれい", :front => "example").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "べんきょう", :front => "study").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "皆さん|みなさん", :front => "Dear all").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "皆|みんな", :front => "everyone").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いいえ、これはちがいます", :front => "No, it's different / not correct").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "わかりますか", :front => "Do you understand?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "読んでください|よんでください", :front => "Read it, please    ").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "日本語で話してください|にほんごではなしてください", :front => "Say it in Japanese, please.").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "むだづかい", :front => "wasted use ").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ばか", :front => "stupid|idiot ").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "外人|がいじん", :front => "foreigner").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ぼく", :front => "I").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ではありません", :front => "isn't").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "Nは何ですか", :front => "What is N?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もちろんです", :front => "Of course, certainly").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "NはN2ですか", :front => "N2 (question word) is N?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "だれ|どなた", :front => "who").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さま", :front => "master (super-polite)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お金|おかね", :front => "money").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ほんやくしてください", :front => "Translate, please!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "れきし", :front => "history").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "けいざい", :front => "economy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いしゃ", :front => "doctor").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "せんもん", :front => "specialty (subject of study)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "これ", :front => "this").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ペン", :front => "pen").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あれ", :front => "that (but far)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たな", :front => "shelf").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ドア", :front => "door").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "えんぴつ", :front => "pencil").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "一年生|いちねんせい", :front => "first year student").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ノート", :front => "notebook").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どれ", :front => "which").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "じ書|じしょ", :front => "dictionary").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "図書館|としょかん", :front => "library").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文学部|ぶんがくぶ", :front => "literature department").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "とけい", :front => "watch").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "大学生|だいがくせい", :front => "university student").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "でんとう", :front => "lamp").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おわりました", :front => "I understood").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ありがとうございます", :front => "Thank you very much").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どういたしまして", :front => "You're welcome").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "スイス", :front => "swiss").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ソーセージ", :front => "sausage").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "アジア", :front => "asia").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ウィスキ", :front => "whisky").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "クイズ", :front => "quiz").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ココア", :front => "cocoa").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サイズ", :front => "size").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サカス", :front => "circus").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "センス", :front => "sense (foreign)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ソース", :front => "souce").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "エアコン", :front => "air conditioning").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "コイン", :front => "coin").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サイエンス", :front => "science").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ケーキ", :front => "cake").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "スキーウェア", :front => "ski wear").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いとこ", :front => "cousin").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すきな", :front => "favorite").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "のみもの", :front => "drink").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すきなえいがは何ですか|すきなえいがはなんですか", :front => "What's your favorite movie?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "母|はは", :front => "mother").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お母さん|おかあさん", :front => "mother (polite)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "父|ちち", :front => "father").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お父さん|おとうさん", :front => "father (polite)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "妹|いもうと", :front => "younger sister ").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "姉|あね", :front => "older sister").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "弟|おとうと", :front => "younger brother").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "兄|あに", :front => "older brother").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "むすこ", :front => "son").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "むすめ", :front => "daughter").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "留学生|りゅうがくせい", :front => "exchange student").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "この", :front => "this (thing)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たてもの", :front => "building").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あそこ", :front => "over there (far)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ここ", :front => "here").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "その", :front => "this (thing) (yours)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あの", :front => "that (thing) (over there)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どこ", :front => "where").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どの", :front => "which (thing)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "部屋|へや", :front => "room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ちり学|ちりがく", :front => "geography").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "図書室|としょしつ", :front => "library room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "グループ", :front => "group").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "アメリカ人", :front => "american person").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "チョーク", :front => "chalk").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "けしゴム", :front => "eraser").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "次|つぎ", :front => "next").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "授業|じゅぎょう", :front => "lesson").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おはようございます", :front => "good morning").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こんにちは", :front => "good day (good morning)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こんばんは", :front => "good evening").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さようなら", :front => "goodbye").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "では|また", :front => "bye").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "これはほんやくしてください", :front => "Translate this, please").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ぶつり学|ぶつりがく", :front => "physics").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ちしつ学|ちしつがく", :front => "geology").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しつ問|しつもん", :front => "question").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かんたん", :front => "simple").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "むずかしい", :front => "difficult").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おいしい", :front => "tasty").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "美しい|うつくしい", :front => "beautiful").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "とても", :front => "very").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しゅくだい", :front => "homework").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "半分|はんぶん", :front => "half").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しゅくだいをかくにんしましょう", :front => "Let's check homework").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "アレルギー", :front => "allergy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ユーザー", :front => "user").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "メニュー", :front => "menu").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "レポート", :front => "report").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ワイシャツ", :front => "white shirt").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ワンピース", :front => "one piece").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さいご", :front => "last").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私はNがあります", :front => "I have N").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たくさん", :front => "a lot").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "赤い|あかい", :front => "red").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "青い|あおい", :front => "blue").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "寒い|さむい", :front => "cold").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "せまい", :front => "narrow").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "やさしい", :front => "easy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "古い|ふるい", :front => "old").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "面白い|おもしろい", :front => "interesting").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "白い|しろい", :front => "white").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "つまらない", :front => "boring").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "長い|ながい", :front => "long").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "週|しゅう", :front => "week").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "毎週|まいしゅう", :front => "every week").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "今週|こんしゅう", :front => "this week").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "先週|せんしゅう", :front => "last week").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どんな", :front => "which (characteristics)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すこし", :front => "a little").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ちょっと", :front => "a little bit").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あいにく", :front => "unfortunately").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "りんご", :front => "apple").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "東京|とうきょう", :front => "Tokyo|eastern capital").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "広い|ひろい", :front => "wide").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "近い|ちかい", :front => "close").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "高い|たかい", :front => "tall|expensive").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "茶色い|ちゃいろい", :front => "tea color|brown").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "新しい|あたらしい", :front => "new").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あまり", :front => "not very").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "黄色い|きいろい", :front => "yellow").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こちら", :front => "this way, this direction, here").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こちらこそ", :front => "The pleasure is all mine").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お宅|おたく", :front => "yours, your house").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "遠い|とおい", :front => "far (away)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "良い|いい", :front => "good").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "明るい|あかるい", :front => "bright, light").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "黒い|くろい", :front => "black").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "緑色|みどりいろ", :front => "green").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "色|いろ", :front => "color").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "短い|みじかい", :front => "short").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "安い|やすい", :front => "cheap").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ひくい", :front => "low, short").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "カメラ", :front => "camera").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "小さい|ちいさい", :front => "small").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すこしも", :front => "not at all").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ちっとも", :front => "not at all!!!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "テキスト", :front => "text").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ろうか", :front => "corridor").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たいへん", :front => "very, greatly|enormously").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もの", :front => "thing").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "では", :front => "So... then...").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ねずみ", :front => "mouse").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ねずみいろ", :front => "grey (mouse color)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "みかん", :front => "mandarin").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "みかんいろ", :front => "mandarine color").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もも", :front => "peach").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ももいろ", :front => "peach color").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "オレンジ", :front => "orange").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "オレンジいろ", :front => "orange color").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "始めてください|はじめてください", :front => "please begin").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "全部|ぜんぶ", :front => "all, everything, entire").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "アダプタ", :front => "adapter").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ロケット", :front => "rocket").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "エレベータ", :front => "elevator").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "スポーツ", :front => "sports").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "パン", :front => "bread").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "買う|かう", :front => "to buy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "書く|かく", :front => "to write").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "急ぐ|いそぐ", :front => "to be in a hurry").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "話す|はなす", :front => "to speak").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "立つ|たつ", :front => "to stand").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "死ぬ|しぬ", :front => "to die").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "とぶ", :front => "to fly").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "飲む|のむ", :front => "to drink").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "売る|うる", :front => "to sell").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ある", :front => "to be (things)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "見る|みる", :front => "to see").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いる", :front => "to be").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "食べる|たべる", :front => "to eat").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "える", :front => "to get/gain").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "走る|はしる", :front => "to run").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "入る|はいる", :front => "to enter").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "帰る|かえる", :front => "to return").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "する", :front => "to do").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "来る|くる", :front => "to come").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "指す|さす", :front => "to stab (pieken)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "取る|とる", :front => "to take").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "今夜|こんや", :front => "this evening").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "時間|じかん", :front => "time").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "分|ぶん", :front => "minute").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "年|とし", :front => "year").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "遅い|おそい", :front => "late").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "早い|はやい", :front => "early|quick").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "時|じ", :front => "hour").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "夕|ゆう", :front => "evening").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "午後|ごご", :front => "afternoon").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "毎朝|まいあさ", :front => "every morning").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "起きる|おきる", :front => "to get up|to wake up").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たいてい", :front => "mostly").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "午前|ごぜん", :front => "a.m.|before noon").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "始まる|はじまる", :front => "to begin").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "毎日|まいにち", :front => "every day").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "昼休み|ひるやすみ", :front => "lunch break").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "食堂|しょくどう", :front => "cafeteria|dining hall").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "時々|ときどき", :front => "sometimes").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "喫茶店|きっさてん", :front => "café").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いそがしい", :front => "busy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "毎晩|まいばん", :front => "every night").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "べんきょうする", :front => "to study").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ねる", :front => "to sleep").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "今ど|こんど", :front => "this time").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ゆっくり", :front => "slowly|at ease").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "うえの", :front => "Ueno, section of Tokyo").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ふつう", :front => "usually|normally").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "また", :front => "also").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "何曜日|なんようび", :front => "What day of the week?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "何時|なんじ", :front => "What time?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さんぽする", :front => "to take a walk").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さんぽ", :front => "walk").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "夜|よる", :front => "night").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "今年|ことし", :front => "this year").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "その後で|そのあとで", :front => "after that").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "直ぐ|すぐ", :front => "immediately|soon").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ぎんざ", :front => "Shopping district in Tokyo").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "クラブ", :front => "club").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "れん習|れんしゅう", :front => "practise").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "安心|あんしん", :front => "peace of mind").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "段々|だんだん", :front => "gradually|step by step").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "段|だん", :front => "step").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "動く|うごく", :front => "to move").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "研究|けんきゅう", :front => "research").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "じっけん", :front => "experiment").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そつぎょう", :front => "graduation").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "悪化|あっか", :front => "deterioration|worsening").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ほうそう", :front => "show|stream|broadcast").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "考える|かんがえる", :front => "to think").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "考え|かんがえ", :front => "thought").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あそぶ", :front => "to play").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "のこる", :front => "to remain|to be left over").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "人々|ひとびと", :front => "people").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ます", :front => "to increase").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ますます", :front => "more and more").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "じぶん", :front => "yourself|your").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かんぺき", :front => "perfect").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "まじめ", :front => "streber").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "間|あいだ", :front => "between").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "休けい|きゅうけい", :front => "break").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "自分|じぶん", :front => "myself").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "きのう", :front => "yesterday").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "直す|なおす", :front => "to correct").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "シャワ", :front => "shower").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "シャワを浴びる|シャワをあびる", :front => "to take a shower").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "歯をみがく|はをみがく", :front => "to brush teeth").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ホーム・ステイ", :front => "home stay").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "門|もん", :front => "gate|entrance").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "松|まつ", :front => "pine tree").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "庭|にわ", :front => "(personal) garden").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さくら", :front => "cherry (blossom) tree").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "竹|たけ", :front => "bamboo").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "池|いけ", :front => "pond").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "こい", :front => "koi").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "橋|はし", :front => "bridge").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "階|かい", :front => "story of a building").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おうせつ間|おうせつま", :front => "european room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "茶の間|ちゃのま", :front => "japanese living room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "トイレ", :front => "toilet").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おふろ", :front => "bathroom (jap. style)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "右側|みぎがわ", :front => "right").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "左側|ひだりがわ", :front => "left").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "台所|だいどころ", :front => "kitchen").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "階段|かいだん", :front => "staircase").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "子ども|こども", :front => "child").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "日本間|にほんま", :front => "japanese room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たたみ", :front => "Tatami").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おしいれ", :front => "closet (with sliding door)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "本だな|ほんだな", :front => "book shelf").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いくつ", :front => "how many").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "何階|なんがい", :front => "what floor?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よう間|ようま", :front => "western style room").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よう式|ようしき", :front => "western style").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "日本式|にほんしき", :front => "japanese style").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "魚|さかな", :front => "fish").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "銀行|ぎんこう", :front => "bank").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "銀行家|ぎんこうか", :front => "banker").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "デパート", :front => "department store").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "公園|こうえん", :front => "public park").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ビデオ", :front => "video").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "アルバム", :front => "album").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "からす", :front => "crow").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "パン屋|ぱんや", :front => "bakery").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "学校|がっこう", :front => "school").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "駅|えき", :front => "station").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "バナナ", :front => "banana").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ベンチ", :front => "bench").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かさ", :front => "umbrella").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "くつ", :front => "shoes").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "鳥|とり", :front => "bird").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "となり", :front => "near").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そば", :front => "next to").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "後ろ|うしろ", :front => "behind").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "外|そと", :front => "outside").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "見つける|みつける", :front => "to find").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さがす", :front => "to look for").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "けいたい電話|けいたいでんわ", :front => "mobile phone").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "太よう|たいよう", :front => "sun").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "一人で|ひとりで", :front => "alone").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文法|ぶんぽう", :front => "grammar").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "イギリス", :front => "United Kingdom|Great Britain").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "天井|てんじょう", :front => "ceiling").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "コート", :front => "coat").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ソファ", :front => "sofa").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "つかれる", :front => "to get tired").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "どうして", :front => "why").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "少ない|すくない", :front => "a few").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私はよくねませんでした|わたしはよくねませんでした", :front => "I didn't sleep well").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "一昨日|おととい", :front => "the day before yesterday").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "せいこう", :front => "success").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もどる", :front => "to be back").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "向かう|むかう", :front => "facing").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たとえば", :front => "For example").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "パソコン", :front => "personal computer").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "自分で食事を作りますか|じぶんでしょくじをつくりますか", :front => "Do you make the meal yourself?").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "言ば|ことば", :front => "word").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おもちゃ", :front => "toy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "色々な|いろいろな", :front => "various").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "明後日|あさって", :front => "the day after tomorrow").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "作る|つくる", :front => "to make").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "Nについて", :front => "about N").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "食事|しょくじ", :front => "meal").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "始め|はじめ", :front => "beginning|start").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "はつおん", :front => "pronounciation").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "れん習|れんしゅう", :front => "exercise").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文しょう|ぶんしょう", :front => "sentence|article").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "読む|よむ", :front => "to read").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文けい|ぶんけい", :front => "sentence pattern|sentence example").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "出す|だす", :front => "to give|to put out").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "もう", :front => "already|yet").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "会話|かいわ", :front => "dialog|conversation").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "答える|こたえる", :front => "to answer").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "その他|そのほか", :front => "besides|otherwise").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "スピーチ", :front => "speech").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "事情|じじょう", :front => "situation").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "教える|おしえる", :front => "to teach").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "習う|ならう", :front => "to learn").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "講義|こうぎ", :front => "lecture").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "聞く|きく", :front => "to hear").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "間違える|まちがえる", :front => "to make a mistake").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "テープ", :front => "tape").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ニュース", :front => "news").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "見せる|みせる", :front => "to show").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おく", :front => "to place sth sw").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "歩く|あるく", :front => "to walk").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "足|あし", :front => "leg").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "手|て", :front => "hand").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "目|め", :front => "eye").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "口|くち", :front => "mouth").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ごはん", :front => "cooked rice").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "多い|おおい", :front => "many").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "音|おと", :front => "sound").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "テレビ", :front => "television").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "本当|ほんとう", :front => "really").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "両親|りょうしん", :front => "parents").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ラジオ", :front => "radio").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "答え|こたえ", :front => "answer").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かく", :front => "to paint|to draw").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "テスト", :front => "test").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "せんたく", :front => "laundry").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "うでどけい", :front => "wrist watch").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そうじ", :front => "cleaning").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そうじする", :front => "to clean").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "冬|ふゆ", :front => "winter").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "夏|なつ", :front => "summer").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "秋|あき", :front => "autumn").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "春|はる", :front => "spring").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "何時も|いつも", :front => "always").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "仕事|しごと", :front => "work").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おみやげ", :front => "souvenirs").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "へんじ", :front => "reply").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ひこうき", :front => "airplane").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よい", :front => "good (how do you say it normally)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "なぜ", :front => "why").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "果物|くだもの", :front => "fruits").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "果物屋|くだものや", :front => "fruit shop").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "愛|あい", :front => "love").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "歌|うた", :front => "song").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "行きたい|いきたい", :front => "(i) want to go").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "よかったです", :front => "it was good").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "りっぱな", :front => "fine|wonderful|sophisticated").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かのじょ", :front => "girlfriend").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "私は走ります|わたしははしります", :front => "I run").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "書いてください|かいてください", :front => "Write it please!").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いくら", :front => "how much").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "めしあがってください", :front => "Please eat! (politely)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "二人|ふたり", :front => "Two persons").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しずかな", :front => "quiet").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ゆうめいな", :front => "famous|popular").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "音楽|おんがく", :front => "music").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お菓子|おかし", :front => "sweets").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "へいわ", :front => "peace").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "なし", :front => "pear").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "きらいな", :front => "dislike").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "店|みせ", :front => "shop|store").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しんせつな", :front => "kind|accommodating").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "店員|てんいん", :front => "clerk|shop assistant").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "好きな|すきな", :front => "to like").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "朝食|ちょうしょく", :front => "breakfast").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "洋食|ようしょく", :front => "western style meal").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サンドイッチ", :front => "sandwich").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たまご", :front => "eggs").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ジュース", :front => "juice").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "飲む|のむ", :front => "to drink|to smoke").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "わ食|わしょく", :front => "japanese-style food").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "みそしる", :front => "miso soup").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "わかい", :front => "young").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しかし", :front => "but|however").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ハム・エッグ", :front => "ham and eggs").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サラダ", :front => "salad").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "いっしょ", :front => "together").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "そして", :front => "and").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "大好きな|だいすきな", :front => "favorite").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ウエイトレス", :front => "waitress").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "持ってくる|もってくる", :front => "bring").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "でも", :front => "but|however").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "インテリア", :front => "interior").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すてきな", :front => "lovely").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "昼間|ひるま", :front => "daytime").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "にぎやかな", :front => "bustling|super busy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "げんきな", :front => "healthy").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "きれいな", :front => "beautiful (thing)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "まち", :front => "town").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かき", :front => "Kaki-Frucht").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "きたない", :front => "dirty").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ダンス", :front => "dance").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ばら", :front => "rose").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "所|ところ", :front => "place").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かなり", :front => "considerably|fairly").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "うるさい", :front => "noisy|loud").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "注文|ちゅうもん", :front => "order").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "注文する|ちゅうもんする", :front => "to give an order").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しめる", :front => "to close").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "すみません", :front => "I'm sorry").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "お待たせいたしました|おまたせいたしました", :front => "Thank you for waiting").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "じこ", :front => "accident").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しょうかい", :front => "introduction").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "名字|みょうじ", :front => "last name").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ゼミ", :front => "seminar").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "文化|ぶんか", :front => "culture").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "家族|かぞく", :front => "family").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "サラリーマン", :front => "Salary man").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "小学校|しょうがっこう", :front => "elementary school").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "中学生|ちゅうがくせい", :front => "junior high school student").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "祖父|そふ", :front => "grand father (coll.)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "祖母|そぼ", :front => "grand mother (coll.)").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "大ぜい|おおぜい", :front => "crowd").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "あつまり", :front => "gathering").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "会う|あう", :front => "to meet").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ロビー", :front => "lobby").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "それでは", :front => "well then|in that case").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "生と|せいと", :front => "pupil").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ミーティング", :front => "meeting").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "それとも", :front => "and then|or").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おじさん", :front => "uncle").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おばさん", :front => "aunt").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おじいさん", :front => "grand father").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "おばあさん", :front => "grand mother").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "ジューナリスト", :front => "journalist").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "真ん中|まんなか", :front => "middle").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "たいそうする", :front => "to exercise").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "映画館|えいがかん", :front => "cinema").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "肉|にく", :front => "meat").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "肉屋|にくや", :front => "butchery").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "肉屋さん|にくやさん", :front => "butcher").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "さとう", :front => "sugar").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "つま", :front => "wife").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "週に三回|しゅうにさんかい", :front => "three times a week").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "去年|きょねん", :front => "last year").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "かんごふ", :front => "nurse").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "しけん", :front => "exam").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "生きる|いきる", :front => "to live").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "晩ご飯|ばんごはん", :front => "dinner").update_attributes(:word_list => list)
Word.find_or_create_by(:back => "牛乳|ぎゅうにゅう", :front => "milk").update_attributes(:word_list => list)