# ruby encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Word.create(:back => "家|いえ", :front => "house")
Word.create(:back => "いいえ", :front => "no")
Word.create(:back => "絵|え", :front => "picture")
Word.create(:back => "ええ", :front => "yes")
Word.create(:back => "えいが", :front => "movie")
Word.create(:back => "英語|えいご", :front => "English")
Word.create(:back => "ドイツ語|ドイツご", :front => "German (language)")
Word.create(:back => "私はドイツ人です", :front => "I'm German")
Word.create(:back => "かご", :front => "basket")
Word.create(:back => "木|き", :front => "tree")
Word.create(:back => "子|こ", :front => "child (short word)")
Word.create(:back => "声|こえ", :front => "voice")
Word.create(:back => "明日|あした", :front => "tomorrow")
Word.create(:back => "朝|あさ", :front => "morning")
Word.create(:back => "いす", :front => "chair")
Word.create(:back => "いつ", :front => "when")
Word.create(:back => "うち", :front => "home")
Word.create(:back => "学生|がくせい", :front => "student")
Word.create(:back => "まちがい", :front => "mistake")
Word.create(:back => "方|かた", :front => "person (polite)")
Word.create(:back => "ぎし", :front => "engineer")
Word.create(:back => "そう", :front => "so...")
Word.create(:back => "大学|だいがく", :front => "university")
Word.create(:back => "つくえ", :front => "table")
Word.create(:back => "どう", :front => "how")
Word.create(:back => "どうぞ", :front => "welcome")
Word.create(:back => "はじめまして", :front => "Nice to meet you.")
Word.create(:back => "よろしくお願いします|よろしくおねがいします", :front => "Please treat me well.")
Word.create(:back => "十|じゅう", :front => "ten")
Word.create(:back => "今日|きょう", :front => "today")
Word.create(:back => "行く|いく", :front => "to go")
Word.create(:back => "行う|おこなう", :front => "do, perform")
Word.create(:back => "私たち|わたしたち", :front => "we")
Word.create(:back => "そうじき", :front => "vacuum cleaner")
Word.create(:back => "国|くに", :front => "country")
Word.create(:back => "あなた", :front => "you")
Word.create(:back => "あの人|あのひと", :front => "he|she")
Word.create(:back => "あの方|あのかた", :front => "he (polite)|she (polite)")
Word.create(:back => "犬|いぬ", :front => "dog")
Word.create(:back => "かべ", :front => "wall")
Word.create(:back => "ざっし", :front => "magazine")
Word.create(:back => "地図|ちず", :front => "map")
Word.create(:back => "ねこ", :front => "cat")
Word.create(:back => "はこ", :front => "box")
Word.create(:back => "花|はな", :front => "flower")
Word.create(:back => "人|ひと", :front => "person")
Word.create(:back => "ふで", :front => "brush")
Word.create(:back => "聞いてください|きいてください", :front => "Listen!")
Word.create(:back => "言ってください|いってください", :front => "Say!")
Word.create(:back => "答えてください|こたえてください", :front => "Answer!")
Word.create(:back => "おかけください", :front => "Sit down please!")
Word.create(:back => "どこからきましたか", :front => "Where do you come from?")
Word.create(:back => "何さいですか|なんさいですか", :front => "How old are you?")
Word.create(:back => "その通りです|そのとおりです", :front => "Exactly!")
Word.create(:back => "ぺこぺこ", :front => "I'm hungry!")
Word.create(:back => "よくできました", :front => "Well done.")
Word.create(:back => "耳|みみ", :front => "ear")
Word.create(:back => "いみ", :front => "sense")
Word.create(:back => "ねむい", :front => "sleepy")
Word.create(:back => "私はねむいです", :front => "I'm sleepy")
Word.create(:back => "紙|かみ", :front => "paper")
Word.create(:back => "きもの", :front => "kimono")
Word.create(:back => "教か書|きょうかしょ", :front => "text book")
Word.create(:back => "教室|きょうしつ", :front => "class room")
Word.create(:back => "手紙|てがみ", :front => "letter")
Word.create(:back => "まど", :front => "window")
Word.create(:back => "水|みず", :front => "water")
Word.create(:back => "休み|やすみ", :front => "holiday|rest")
Word.create(:back => "山|サン|やま", :front => "mountain")
Word.create(:back => "ゆか", :front => "floor")
Word.create(:back => "ようふく", :front => "clothes")
Word.create(:back => "はい", :front => "yes")
Word.create(:back => "直してください|なおしてください", :front => "correct it!")
Word.create(:back => "もういちどどうぞ", :front => "one more time!")
Word.create(:back => "お茶|おちゃ", :front => "tea")
Word.create(:back => "紅茶|こうちゃ", :front => "black tea")
Word.create(:back => "東京で何をしますか|とうきょうでなにをしますか", :front => "What do you do in Tokyo?")
Word.create(:back => "お名前|おなまえ", :front => "name")
Word.create(:back => "むだばなし", :front => "quatsch")
Word.create(:back => "本|ほん", :front => "book")
Word.create(:back => "れいぞうこ", :front => "fridge")
Word.create(:back => "かばん", :front => "bag|backpack")
Word.create(:back => "終わり|おわり", :front => "end")
Word.create(:back => "こくばん", :front => "blackboard")
Word.create(:back => "写真|しゃしん", :front => "foto")
Word.create(:back => "新聞|新ぶん|しんぶん", :front => "newspaper")
Word.create(:back => "先生|せんせい", :front => "teacher")
Word.create(:back => "電話|でんわ", :front => "telephone")
Word.create(:back => "番号|ばんごう", :front => "number")
Word.create(:back => "電話番号は何ですか|でんわばんごうはなんですか", :front => "What's your number?")
Word.create(:back => "日本|にほん", :front => "Japan")
Word.create(:back => "文れい|ぶんれい", :front => "example")
Word.create(:back => "べんきょう", :front => "study")
Word.create(:back => "皆さん|みなさん", :front => "Dear all")
Word.create(:back => "皆|みんな", :front => "everyone")
Word.create(:back => "いいえ、これはちがいます", :front => "No, it's different / not correct")
Word.create(:back => "わかりますか", :front => "Do you understand?")
Word.create(:back => "読んでください|よんでください", :front => "Read it, please    ")
Word.create(:back => "日本語で話してください|にほんごではなしてください", :front => "Say it in Japanese, please.")
Word.create(:back => "むだづかい", :front => "wasted use ")
Word.create(:back => "ばか", :front => "stupid|idiot ")
Word.create(:back => "外人|がいじん", :front => "foreigner")
Word.create(:back => "ぼく", :front => "I")
Word.create(:back => "ではありません", :front => "isn't")
Word.create(:back => "Nは何ですか", :front => "What is N?")
Word.create(:back => "もちろんです", :front => "Of course, certainly")
Word.create(:back => "NはN2ですか", :front => "N2 (question word) is N?")
Word.create(:back => "だれ|どなた", :front => "who")
Word.create(:back => "さま", :front => "master (super-polite)")
Word.create(:back => "お金|おかね", :front => "money")
Word.create(:back => "ほんやくしてください", :front => "Translate, please!")
Word.create(:back => "れきし", :front => "history")
Word.create(:back => "けいざい", :front => "economy")
Word.create(:back => "いしゃ", :front => "doctor")
Word.create(:back => "せんもん", :front => "specialty (subject of study)")
Word.create(:back => "これ", :front => "this")
Word.create(:back => "ペン", :front => "pen")
Word.create(:back => "あれ", :front => "that (but far)")
Word.create(:back => "たな", :front => "shelf")
Word.create(:back => "ドア", :front => "door")
Word.create(:back => "えんぴつ", :front => "pencil")
Word.create(:back => "一年生|いちねんせい", :front => "first year student")
Word.create(:back => "ノート", :front => "notebook")
Word.create(:back => "どれ", :front => "which")
Word.create(:back => "じ書|じしょ", :front => "dictionary")
Word.create(:back => "図書館|としょかん", :front => "library")
Word.create(:back => "文学部|ぶんがくぶ", :front => "literature department")
Word.create(:back => "とけい", :front => "watch")
Word.create(:back => "大学生|だいがくせい", :front => "university student")
Word.create(:back => "でんとう", :front => "lamp")
Word.create(:back => "おわりました", :front => "I understood")
Word.create(:back => "ありがとうございます", :front => "Thank you very much")
Word.create(:back => "どういたしまして", :front => "You're welcome")
Word.create(:back => "スイス", :front => "swiss")
Word.create(:back => "ソーセージ", :front => "sausage")
Word.create(:back => "アジア", :front => "asia")
Word.create(:back => "ウィスキ", :front => "whisky")
Word.create(:back => "クイズ", :front => "quiz")
Word.create(:back => "ココア", :front => "cocoa")
Word.create(:back => "サイズ", :front => "size")
Word.create(:back => "サカス", :front => "circus")
Word.create(:back => "センス", :front => "sense (foreign)")
Word.create(:back => "ソース", :front => "souce")
Word.create(:back => "エアコン", :front => "air conditioning")
Word.create(:back => "コイン", :front => "coin")
Word.create(:back => "サイエンス", :front => "science")
Word.create(:back => "ケーキ", :front => "cake")
Word.create(:back => "スキーウェア", :front => "ski wear")
Word.create(:back => "いとこ", :front => "cousin")
Word.create(:back => "すきな", :front => "favorite")
Word.create(:back => "のみもの", :front => "drink")
Word.create(:back => "すきなえいがは何ですか|すきなえいがはなんですか", :front => "What's your favorite movie?")
Word.create(:back => "母|はは", :front => "mother")
Word.create(:back => "お母さん|おかあさん", :front => "mother (polite)")
Word.create(:back => "父|ちち", :front => "father")
Word.create(:back => "お父さん|おとうさん", :front => "father (polite)")
Word.create(:back => "妹|いもうと", :front => "younger sister ")
Word.create(:back => "姉|あね", :front => "older sister")
Word.create(:back => "弟|おとうと", :front => "younger brother")
Word.create(:back => "兄|あに", :front => "older brother")
Word.create(:back => "むすこ", :front => "son")
Word.create(:back => "むすめ", :front => "daughter")
Word.create(:back => "留学生|りゅうがくせい", :front => "exchange student")
Word.create(:back => "この", :front => "this (thing)")
Word.create(:back => "たてもの", :front => "building")
Word.create(:back => "あそこ", :front => "over there (far)")
Word.create(:back => "ここ", :front => "here")
Word.create(:back => "その", :front => "this (thing) (yours)")
Word.create(:back => "あの", :front => "that (thing) (over there)")
Word.create(:back => "どこ", :front => "where")
Word.create(:back => "どの", :front => "which (thing)")
Word.create(:back => "部屋|へや", :front => "room")
Word.create(:back => "ちり学|ちりがく", :front => "geography")
Word.create(:back => "図書室|としょしつ", :front => "library room")
Word.create(:back => "グループ", :front => "group")
Word.create(:back => "アメリカ人", :front => "american person")
Word.create(:back => "チョーク", :front => "chalk")
Word.create(:back => "けしゴム", :front => "eraser")
Word.create(:back => "次|つぎ", :front => "next")
Word.create(:back => "授業|じゅぎょう", :front => "lesson")
Word.create(:back => "おはようございます", :front => "good morning")
Word.create(:back => "こんにちは", :front => "good day (good morning)")
Word.create(:back => "こんばんは", :front => "good evening")
Word.create(:back => "さようなら", :front => "goodbye")
Word.create(:back => "では|また", :front => "bye")
Word.create(:back => "これはほんやくしてください", :front => "Translate this, please")
Word.create(:back => "ぶつり学|ぶつりがく", :front => "physics")
Word.create(:back => "ちしつ学|ちしつがく", :front => "geology")
Word.create(:back => "しつ問|しつもん", :front => "question")
Word.create(:back => "かんたん", :front => "simple")
Word.create(:back => "むずかしい", :front => "difficult")
Word.create(:back => "おいしい", :front => "tasty")
Word.create(:back => "美しい|うつくしい", :front => "beautiful")
Word.create(:back => "とても", :front => "very")
Word.create(:back => "しゅくだい", :front => "homework")
Word.create(:back => "半分|はんぶん", :front => "half")
Word.create(:back => "しゅくだいをかくにんしましょう", :front => "Let's check homework")
Word.create(:back => "アレルギー", :front => "allergy")
Word.create(:back => "ユーザー", :front => "user")
Word.create(:back => "メニュー", :front => "menu")
Word.create(:back => "レポート", :front => "report")
Word.create(:back => "ワイシャツ", :front => "white shirt")
Word.create(:back => "ワンピース", :front => "one piece")
Word.create(:back => "さいご", :front => "last")
Word.create(:back => "私はNがあります", :front => "I have N")
Word.create(:back => "たくさん", :front => "a lot")
Word.create(:back => "赤い|あかい", :front => "red")
Word.create(:back => "青い|あおい", :front => "blue")
Word.create(:back => "寒い|さむい", :front => "cold")
Word.create(:back => "せまい", :front => "narrow")
Word.create(:back => "やさしい", :front => "easy")
Word.create(:back => "古い|ふるい", :front => "old")
Word.create(:back => "面白い|おもしろい", :front => "interesting")
Word.create(:back => "白い|しろい", :front => "white")
Word.create(:back => "つまらない", :front => "boring")
Word.create(:back => "長い|ながい", :front => "long")
Word.create(:back => "週|しゅう", :front => "week")
Word.create(:back => "毎週|まいしゅう", :front => "every week")
Word.create(:back => "今週|こんしゅう", :front => "this week")
Word.create(:back => "先週|せんしゅう", :front => "last week")
Word.create(:back => "どんな", :front => "which (characteristics)")
Word.create(:back => "すこし", :front => "a little")
Word.create(:back => "ちょっと", :front => "a little bit")
Word.create(:back => "あいにく", :front => "unfortunately")
Word.create(:back => "りんご", :front => "apple")
Word.create(:back => "東京|とうきょう", :front => "Tokyo|eastern capital")
Word.create(:back => "広い|ひろい", :front => "wide")
Word.create(:back => "近い|ちかい", :front => "close")
Word.create(:back => "高い|たかい", :front => "tall|expensive")
Word.create(:back => "茶色い|ちゃいろい", :front => "tea color|brown")
Word.create(:back => "新しい|あたらしい", :front => "new")
Word.create(:back => "あまり", :front => "not very")
Word.create(:back => "黄色い|きいろい", :front => "yellow")
Word.create(:back => "こちら", :front => "this way, this direction, here")
Word.create(:back => "こちらこそ", :front => "The pleasure is all mine")
Word.create(:back => "お宅|おたく", :front => "yours, your house")
Word.create(:back => "遠い|とおい", :front => "far (away)")
Word.create(:back => "良い|いい", :front => "good")
Word.create(:back => "明るい|あかるい", :front => "bright, light")
Word.create(:back => "黒い|くろい", :front => "black")
Word.create(:back => "緑色|みどりいろ", :front => "green")
Word.create(:back => "色|いろ", :front => "color")
Word.create(:back => "短い|みじかい", :front => "short")
Word.create(:back => "安い|やすい", :front => "cheap")
Word.create(:back => "ひくい", :front => "low, short")
Word.create(:back => "カメラ", :front => "camera")
Word.create(:back => "小さい|ちいさい", :front => "small")
Word.create(:back => "すこしも", :front => "not at all")
Word.create(:back => "ちっとも", :front => "not at all!!!")
Word.create(:back => "テキスト", :front => "text")
Word.create(:back => "ろうか", :front => "corridor")
Word.create(:back => "たいへん", :front => "very, greatly|enormously")
Word.create(:back => "もの", :front => "thing")
Word.create(:back => "では", :front => "So... then...")
Word.create(:back => "ねずみ", :front => "mouse")
Word.create(:back => "ねずみいろ", :front => "grey (mouse color)")
Word.create(:back => "みかん", :front => "mandarin")
Word.create(:back => "みかんいろ", :front => "mandarine color")
Word.create(:back => "もも", :front => "peach")
Word.create(:back => "ももいろ", :front => "peach color")
Word.create(:back => "オレンジ", :front => "orange")
Word.create(:back => "オレンジいろ", :front => "orange color")
Word.create(:back => "始めてください|はじめてください", :front => "please begin")
Word.create(:back => "全部|ぜんぶ", :front => "all, everything, entire")
Word.create(:back => "アダプタ", :front => "adapter")
Word.create(:back => "ロケット", :front => "rocket")
Word.create(:back => "エレベータ", :front => "elevator")
Word.create(:back => "スポーツ", :front => "sports")
Word.create(:back => "パン", :front => "bread")
Word.create(:back => "買う|かう", :front => "to buy")
Word.create(:back => "書く|かく", :front => "to write")
Word.create(:back => "急ぐ|いそぐ", :front => "to be in a hurry")
Word.create(:back => "話す|はなす", :front => "to speak")
Word.create(:back => "立つ|たつ", :front => "to stand")
Word.create(:back => "死ぬ|しぬ", :front => "to die")
Word.create(:back => "とぶ", :front => "to fly")
Word.create(:back => "飲む|のむ", :front => "to drink")
Word.create(:back => "売る|うる", :front => "to sell")
Word.create(:back => "ある", :front => "to be (things)")
Word.create(:back => "見る|みる", :front => "to see")
Word.create(:back => "いる", :front => "to be")
Word.create(:back => "食べる|たべる", :front => "to eat")
Word.create(:back => "える", :front => "to get/gain")
Word.create(:back => "走る|はしる", :front => "to run")
Word.create(:back => "入る|はいる", :front => "to enter")
Word.create(:back => "帰る|かえる", :front => "to return")
Word.create(:back => "する", :front => "to do")
Word.create(:back => "来る|くる", :front => "to come")
Word.create(:back => "指す|さす", :front => "to stab (pieken)")
Word.create(:back => "取る|とる", :front => "to take")
Word.create(:back => "今夜|こんや", :front => "this evening")
Word.create(:back => "時間|じかん", :front => "time")
Word.create(:back => "分|ぶん", :front => "minute")
Word.create(:back => "年|とし", :front => "year")
Word.create(:back => "遅い|おそい", :front => "late")
Word.create(:back => "早い|はやい", :front => "early|quick")
Word.create(:back => "時|じ", :front => "hour")
Word.create(:back => "夕|ゆう", :front => "evening")
Word.create(:back => "午後|ごご", :front => "afternoon")
Word.create(:back => "毎朝|まいあさ", :front => "every morning")
Word.create(:back => "起きる|おきる", :front => "to get up|to wake up")
Word.create(:back => "たいてい", :front => "mostly")
Word.create(:back => "午前|ごぜん", :front => "a.m.|before noon")
Word.create(:back => "始まる|はじまる", :front => "to begin")
Word.create(:back => "毎日|まいにち", :front => "every day")
Word.create(:back => "昼休み|ひるやすみ", :front => "lunch break")
Word.create(:back => "食堂|しょくどう", :front => "cafeteria|dining hall")
Word.create(:back => "時々|ときどき", :front => "sometimes")
Word.create(:back => "喫茶店|きっさてん", :front => "café")
Word.create(:back => "いそがしい", :front => "busy")
Word.create(:back => "毎晩|まいばん", :front => "every night")
Word.create(:back => "べんきょうする", :front => "to study")
Word.create(:back => "ねる", :front => "to sleep")
Word.create(:back => "今ど|こんど", :front => "this time")
Word.create(:back => "ゆっくり", :front => "slowly|at ease")
Word.create(:back => "うえの", :front => "Ueno, section of Tokyo")
Word.create(:back => "ふつう", :front => "usually|normally")
Word.create(:back => "また", :front => "also")
Word.create(:back => "何曜日|なんようび", :front => "What day of the week?")
Word.create(:back => "何時|なんじ", :front => "What time?")
Word.create(:back => "さんぽする", :front => "to take a walk")
Word.create(:back => "さんぽ", :front => "walk")
Word.create(:back => "夜|よる", :front => "night")
Word.create(:back => "今年|ことし", :front => "this year")
Word.create(:back => "その後で|そのあとで", :front => "after that")
Word.create(:back => "直ぐ|すぐ", :front => "immediately|soon")
Word.create(:back => "ぎんざ", :front => "Shopping district in Tokyo")
Word.create(:back => "クラブ", :front => "club")
Word.create(:back => "れん習|れんしゅう", :front => "practise")
Word.create(:back => "安心|あんしん", :front => "peace of mind")
Word.create(:back => "段々|だんだん", :front => "gradually|step by step")
Word.create(:back => "段|だん", :front => "step")
Word.create(:back => "動く|うごく", :front => "to move")
Word.create(:back => "研究|けんきゅう", :front => "research")
Word.create(:back => "じっけん", :front => "experiment")
Word.create(:back => "そつぎょう", :front => "graduation")
Word.create(:back => "悪化|あっか", :front => "deterioration|worsening")
Word.create(:back => "ほうそう", :front => "show|stream|broadcast")
Word.create(:back => "考える|かんがえる", :front => "to think")
Word.create(:back => "考え|かんがえ", :front => "thought")
Word.create(:back => "あそぶ", :front => "to play")
Word.create(:back => "のこる", :front => "to remain|to be left over")
Word.create(:back => "人々|ひとびと", :front => "people")
Word.create(:back => "ます", :front => "to increase")
Word.create(:back => "ますます", :front => "more and more")
Word.create(:back => "じぶん", :front => "yourself|your")
Word.create(:back => "かんぺき", :front => "perfect")
Word.create(:back => "まじめ", :front => "streber")
Word.create(:back => "間|あいだ", :front => "between")
Word.create(:back => "休けい|きゅうけい", :front => "break")
Word.create(:back => "自分|じぶん", :front => "myself")
Word.create(:back => "きのう", :front => "yesterday")
Word.create(:back => "直す|なおす", :front => "to correct")
Word.create(:back => "シャワ", :front => "shower")
Word.create(:back => "シャワを浴びる|シャワをあびる", :front => "to take a shower")
Word.create(:back => "歯をみがく|はをみがく", :front => "to brush teeth")
Word.create(:back => "ホーム・ステイ", :front => "home stay")
Word.create(:back => "門|もん", :front => "gate|entrance")
Word.create(:back => "松|まつ", :front => "pine tree")
Word.create(:back => "庭|にわ", :front => "(personal) garden")
Word.create(:back => "さくら", :front => "cherry (blossom) tree")
Word.create(:back => "竹|たけ", :front => "bamboo")
Word.create(:back => "池|いけ", :front => "pond")
Word.create(:back => "こい", :front => "koi")
Word.create(:back => "橋|はし", :front => "bridge")
Word.create(:back => "階|かい", :front => "story of a building")
Word.create(:back => "おうせつ間|おうせつま", :front => "european room")
Word.create(:back => "茶の間|ちゃのま", :front => "japanese living room")
Word.create(:back => "トイレ", :front => "toilet")
Word.create(:back => "おふろ", :front => "bathroom (jap. style)")
Word.create(:back => "右側|みぎがわ", :front => "right")
Word.create(:back => "左側|ひだりがわ", :front => "left")
Word.create(:back => "台所|だいどころ", :front => "kitchen")
Word.create(:back => "階段|かいだん", :front => "staircase")
Word.create(:back => "子ども|こども", :front => "child")
Word.create(:back => "日本間|にほんま", :front => "japanese room")
Word.create(:back => "たたみ", :front => "Tatami")
Word.create(:back => "おしいれ", :front => "closet (with sliding door)")
Word.create(:back => "本だな|ほんだな", :front => "book shelf")
Word.create(:back => "いくつ", :front => "how many")
Word.create(:back => "何階|なんがい", :front => "what floor?")
Word.create(:back => "よう間|ようま", :front => "western style room")
Word.create(:back => "よう式|ようしき", :front => "western style")
Word.create(:back => "日本式|にほんしき", :front => "japanese style")
Word.create(:back => "魚|さかな", :front => "fish")
Word.create(:back => "銀行|ぎんこう", :front => "bank")
Word.create(:back => "銀行家|ぎんこうか", :front => "banker")
Word.create(:back => "デパート", :front => "department store")
Word.create(:back => "公園|こうえん", :front => "public park")
Word.create(:back => "ビデオ", :front => "video")
Word.create(:back => "アルバム", :front => "album")
Word.create(:back => "からす", :front => "crow")
Word.create(:back => "パン屋|ぱんや", :front => "bakery")
Word.create(:back => "学校|がっこう", :front => "school")
Word.create(:back => "駅|えき", :front => "station")
Word.create(:back => "バナナ", :front => "banana")
Word.create(:back => "ベンチ", :front => "bench")
Word.create(:back => "かさ", :front => "umbrella")
Word.create(:back => "くつ", :front => "shoes")
Word.create(:back => "鳥|とり", :front => "bird")
Word.create(:back => "となり", :front => "near")
Word.create(:back => "そば", :front => "next to")
Word.create(:back => "後ろ|うしろ", :front => "behind")
Word.create(:back => "外|そと", :front => "outside")
Word.create(:back => "見つける|みつける", :front => "to find")
Word.create(:back => "さがす", :front => "to look for")
Word.create(:back => "けいたい電話|けいたいでんわ", :front => "mobile phone")
Word.create(:back => "太よう|たいよう", :front => "sun")
Word.create(:back => "一人で|ひとりで", :front => "alone")
Word.create(:back => "文法|ぶんぽう", :front => "grammar")
Word.create(:back => "イギリス", :front => "United Kingdom|Great Britain")
Word.create(:back => "天井|てんじょう", :front => "ceiling")
Word.create(:back => "コート", :front => "coat")
Word.create(:back => "ソファ", :front => "sofa")
Word.create(:back => "つかれる", :front => "to get tired")
Word.create(:back => "どうして", :front => "why")
Word.create(:back => "少ない|すくない", :front => "a few")
Word.create(:back => "私はよくねませんでした|わたしはよくねませんでした", :front => "I didn't sleep well")
Word.create(:back => "一昨日|おととい", :front => "the day before yesterday")
Word.create(:back => "せいこう", :front => "success")
Word.create(:back => "もどる", :front => "to be back")
Word.create(:back => "向かう|むかう", :front => "facing")
Word.create(:back => "たとえば", :front => "For example")
Word.create(:back => "パソコン", :front => "personal computer")
Word.create(:back => "自分で食事を作りますか|じぶんでしょくじをつくりますか", :front => "Do you make the meal yourself?")
Word.create(:back => "言ば|ことば", :front => "word")
Word.create(:back => "おもちゃ", :front => "toy")
Word.create(:back => "色々な|いろいろな", :front => "various")
Word.create(:back => "明後日|あさって", :front => "the day after tomorrow")
Word.create(:back => "作る|つくる", :front => "to make")
Word.create(:back => "Nについて", :front => "about N")
Word.create(:back => "食事|しょくじ", :front => "meal")
Word.create(:back => "始め|はじめ", :front => "beginning|start")
Word.create(:back => "はつおん", :front => "pronounciation")
Word.create(:back => "れん習|れんしゅう", :front => "exercise")
Word.create(:back => "文しょう|ぶんしょう", :front => "sentence|article")
Word.create(:back => "読む|よむ", :front => "to read")
Word.create(:back => "文けい|ぶんけい", :front => "sentence pattern|sentence example")
Word.create(:back => "出す|だす", :front => "to give|to put out")
Word.create(:back => "もう", :front => "already|yet")
Word.create(:back => "会話|かいわ", :front => "dialog|conversation")
Word.create(:back => "答える|こたえる", :front => "to answer")
Word.create(:back => "その他|そのほか", :front => "besides|otherwise")
Word.create(:back => "スピーチ", :front => "speech")
Word.create(:back => "事情|じじょう", :front => "situation")
Word.create(:back => "教える|おしえる", :front => "to teach")
Word.create(:back => "習う|ならう", :front => "to learn")
Word.create(:back => "講義|こうぎ", :front => "lecture")
Word.create(:back => "聞く|きく", :front => "to hear")
Word.create(:back => "間違える|まちがえる", :front => "to make a mistake")
Word.create(:back => "テープ", :front => "tape")
Word.create(:back => "ニュース", :front => "news")
Word.create(:back => "見せる|みせる", :front => "to show")
Word.create(:back => "おく", :front => "to place sth sw")
Word.create(:back => "歩く|あるく", :front => "to walk")
Word.create(:back => "足|あし", :front => "leg")
Word.create(:back => "手|て", :front => "hand")
Word.create(:back => "目|め", :front => "eye")
Word.create(:back => "口|くち", :front => "mouth")
Word.create(:back => "ごはん", :front => "cooked rice")
Word.create(:back => "多い|おおい", :front => "many")
Word.create(:back => "音|おと", :front => "sound")
Word.create(:back => "テレビ", :front => "television")
Word.create(:back => "本当|ほんとう", :front => "really")
Word.create(:back => "両親|りょうしん", :front => "parents")
Word.create(:back => "ラジオ", :front => "radio")
Word.create(:back => "答え|こたえ", :front => "answer")
Word.create(:back => "かく", :front => "to paint|to draw")
Word.create(:back => "テスト", :front => "test")
Word.create(:back => "せんたく", :front => "laundry")
Word.create(:back => "うでどけい", :front => "wrist watch")
Word.create(:back => "そうじ", :front => "cleaning")
Word.create(:back => "そうじする", :front => "to clean")
Word.create(:back => "冬|ふゆ", :front => "winter")
Word.create(:back => "夏|なつ", :front => "summer")
Word.create(:back => "秋|あき", :front => "autumn")
Word.create(:back => "春|はる", :front => "spring")
Word.create(:back => "何時も|いつも", :front => "always")
Word.create(:back => "仕事|しごと", :front => "work")
Word.create(:back => "おみやげ", :front => "souvenirs")
Word.create(:back => "へんじ", :front => "reply")
Word.create(:back => "ひこうき", :front => "airplane")
Word.create(:back => "よい", :front => "good (how do you say it normally)")
Word.create(:back => "なぜ", :front => "why")
Word.create(:back => "果物|くだもの", :front => "fruits")
Word.create(:back => "果物屋|くだものや", :front => "fruit shop")
Word.create(:back => "愛|あい", :front => "love")
Word.create(:back => "歌|うた", :front => "song")
Word.create(:back => "行きたい|いきたい", :front => "(i) want to go")
Word.create(:back => "よかったです", :front => "it was good")
Word.create(:back => "りっぱな", :front => "fine|wonderful|sophisticated")
Word.create(:back => "かのじょ", :front => "girlfriend")
Word.create(:back => "私は走ります|わたしははしります", :front => "I run")
Word.create(:back => "書いてください|かいてください", :front => "Write it please!")
Word.create(:back => "いくら", :front => "how much")
Word.create(:back => "めしあがってください", :front => "Please eat! (politely)")
Word.create(:back => "二人|ふたり", :front => "Two persons")
Word.create(:back => "しずかな", :front => "quiet")
Word.create(:back => "ゆうめいな", :front => "famous|popular")
Word.create(:back => "音楽|おんがく", :front => "music")
Word.create(:back => "お菓子|おかし", :front => "sweets")
Word.create(:back => "へいわ", :front => "peace")
Word.create(:back => "なし", :front => "pear")
Word.create(:back => "きらいな", :front => "dislike")
Word.create(:back => "店|みせ", :front => "shop|store")
Word.create(:back => "しんせつな", :front => "kind|accommodating")
Word.create(:back => "店員|てんいん", :front => "clerk|shop assistant")
Word.create(:back => "好きな|すきな", :front => "to like")
Word.create(:back => "朝食|ちょうしょく", :front => "breakfast")
Word.create(:back => "洋食|ようしょく", :front => "western style meal")
Word.create(:back => "サンドイッチ", :front => "sandwich")
Word.create(:back => "たまご", :front => "eggs")
Word.create(:back => "ジュース", :front => "juice")
Word.create(:back => "飲む|のむ", :front => "to drink|to smoke")
Word.create(:back => "わ食|わしょく", :front => "japanese-style food")
Word.create(:back => "みそしる", :front => "miso soup")
Word.create(:back => "わかい", :front => "young")
Word.create(:back => "しかし", :front => "but|however")
Word.create(:back => "ハム・エッグ", :front => "ham and eggs")
Word.create(:back => "サラダ", :front => "salad")
Word.create(:back => "いっしょ", :front => "together")
Word.create(:back => "そして", :front => "and")
Word.create(:back => "大好きな|だいすきな", :front => "favorite")
Word.create(:back => "ウエイトレス", :front => "waitress")
Word.create(:back => "持ってくる|もってくる", :front => "bring")
Word.create(:back => "でも", :front => "but|however")
Word.create(:back => "インテリア", :front => "interior")
Word.create(:back => "すてきな", :front => "lovely")
Word.create(:back => "昼間|ひるま", :front => "daytime")
Word.create(:back => "にぎやかな", :front => "bustling|super busy")
Word.create(:back => "げんきな", :front => "healthy")
Word.create(:back => "きれいな", :front => "beautiful (thing)")
Word.create(:back => "まち", :front => "town")
Word.create(:back => "かき", :front => "Kaki-Frucht")
Word.create(:back => "きたない", :front => "dirty")
Word.create(:back => "ダンス", :front => "dance")
Word.create(:back => "ばら", :front => "rose")
Word.create(:back => "所|ところ", :front => "place")
Word.create(:back => "かなり", :front => "considerably|fairly")
Word.create(:back => "うるさい", :front => "noisy|loud")
Word.create(:back => "注文|ちゅうもん", :front => "order")
Word.create(:back => "注文する|ちゅうもんする", :front => "to give an order")
Word.create(:back => "しめる", :front => "to close")
Word.create(:back => "すみません", :front => "I'm sorry")
Word.create(:back => "お待たせいたしました|おまたせいたしました", :front => "Thank you for waiting")
Word.create(:back => "じこ", :front => "accident")
Word.create(:back => "しょうかい", :front => "introduction")
Word.create(:back => "名字|みょうじ", :front => "last name")
Word.create(:back => "ゼミ", :front => "seminar")
Word.create(:back => "文化|ぶんか", :front => "culture")
Word.create(:back => "家族|かぞく", :front => "family")
Word.create(:back => "サラリーマン", :front => "Salary man")
Word.create(:back => "小学校|しょうがっこう", :front => "elementary school")
Word.create(:back => "中学生|ちゅうがくせい", :front => "junior high school student")
Word.create(:back => "祖父|そふ", :front => "grand father (coll.)")
Word.create(:back => "祖母|そぼ", :front => "grand mother (coll.)")
Word.create(:back => "大ぜい|おおぜい", :front => "crowd")
Word.create(:back => "あつまり", :front => "gathering")
Word.create(:back => "会う|あう", :front => "to meet")
Word.create(:back => "ロビー", :front => "lobby")
Word.create(:back => "それでは", :front => "well then|in that case")
Word.create(:back => "生と|せいと", :front => "pupil")
Word.create(:back => "ミーティング", :front => "meeting")
Word.create(:back => "それとも", :front => "and then|or")
Word.create(:back => "おじさん", :front => "uncle")
Word.create(:back => "おばさん", :front => "aunt")
Word.create(:back => "おじいさん", :front => "grand father")
Word.create(:back => "おばあさん", :front => "grand mother")
Word.create(:back => "ジューナリスト", :front => "journalist")
Word.create(:back => "真ん中|まんなか", :front => "middle")
Word.create(:back => "たいそうする", :front => "to exercise")
Word.create(:back => "映画館|えいがかん", :front => "cinema")
Word.create(:back => "肉|にく", :front => "meat")
Word.create(:back => "肉屋|にくや", :front => "butchery")
Word.create(:back => "肉屋さん|にくやさん", :front => "butcher")
Word.create(:back => "さとう", :front => "sugar")
Word.create(:back => "つま", :front => "wife")
Word.create(:back => "週に三回|しゅうにさんかい", :front => "three times a week")
Word.create(:back => "去年|きょねん", :front => "last year")
Word.create(:back => "かんごふ", :front => "nurse")
Word.create(:back => "しけん", :front => "exam")
Word.create(:back => "生きる|いきる", :front => "to live")
Word.create(:back => "晩ご飯|ばんごはん", :front => "dinner")
Word.create(:back => "牛乳|ぎゅうにゅう", :front => "milk")